accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

# from src.accounts.models import Profile
# from resume.views import ProfileCreateView
from .views import NormalSignUpView, EmployerSignUpView, SignUpView, UserLogin, UserUpdateView, validate_email, \
    validate_username

app_name = 'accounts'

urlpatterns = [
    # path('', include('django.contrib.auth.urls')),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup/normal_user/', NormalSignUpView.as_view(), name='normal_user_signup'),
    path('signup/employer/', EmployerSignUpView.as_view(), name='employer_signup'),
    path('ajax/validate_username/', validate_username, name='validate_username'),
    path('ajax/validate_username/', validate_email, name='validate_email'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',
                                                        email_template_name='accounts/password_reset_email.html',
                                                        subject_template_name='accounts/password_reset_subject.txt'),
         name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    # path('settings/account/', accounts_views.UserDetail.as_view(), name='my_account'),
    path('settings/account_edit/', UserUpdateView.as_view(), name='account_edit'),
    # path('users/', UserList.as_view(), name='users'),
    # path('<slug>/', Profile.as_view(), name='account'),
    # path('create/', ProfileCreateView.as_view(), name='create_profile'),
    path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html',
                                                                     success_url=reverse_lazy(
                                                                         'accounts:password_change_done')),
         name='password_change'),
    path('settings/password/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),

]

blog/urls.py
from django.urls import path

from .views import PostCreate, PostDetail, PostEdit, PostDelete, PostList, add_comment

app_name = 'Post'

urlpatterns = [
    path('new/', PostCreate.as_view(), name='new'),
    path('<slug:slug>/', PostDetail.as_view(), name='detail'),
    path('<slug:slug>/edit/', PostEdit.as_view(), name='edit'),
    path('<slug:slug>/delete/', PostDelete.as_view(), name='delete'),

    path('', PostList.as_view(), name='list'),
    path('<post_id>/add_comment/', add_comment, name='add_comment'),

]

job/urls.py
from django.urls import path

from .views import JobEdit, JobDelete, JobDetail, job_list_view

app_name = 'job'

urlpatterns = [
    # path('new/', JobCreate.as_view(), name='new'),
    # path('<slug:slug>/edit/', JobEdit.as_view(), name='edit'),
    path('<slug:slug>delete/', JobDelete.as_view(), name='delete'),
    path('<slug:slug>/', JobDetail.as_view(), name='detail'),
    # path('', JobList.as_view(), name='list'),
    path('', job_list_view, name='list'),

]

jobcorner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.flatpages.views import flatpage
from django.urls import path, include
from django_filters.views import FilterView

from homepage.views import HomeIndex, UserFilter, Dashboard

urlpatterns = [
    path('dashboard', Dashboard.as_view(), name='dashboard'),
    path('', HomeIndex.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('company/', include('company.urls', namespace='company')),
    path('category/', include('category.urls', namespace='category')),
    path('country/', include('country.urls', namespace='country')),
    path('location/', include('location.urls', namespace='location')),
    path('job/', include('job.urls', namespace='job')),
    path('resume/', include('resume.urls', namespace='resume')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('search/', FilterView.as_view(filterset_class=UserFilter, template_name='search.html'), name='search'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',
                                                        email_template_name='accounts/password_reset_email.html',
                                                        subject_template_name='accounts/password_reset_subject.txt'),
         name='password_reset'),
    path("likes/", include("pinax.likes.urls", namespace="pinax_likes")),
    path('notifications/', include("pinax.notifications.urls", namespace="notifications")),
    path('messages/', include("pinax.messages.urls", namespace="pinax_messages")),

    path('about-us/', flatpage, {'url': '/about-us/'}, name='about'),
    path('license/', flatpage, {'url': '/license/'}, name='license'),
    path('terms/', flatpage, {'url': '/terms/'}, name='terms'),
    path('pricelist/', include('pricelist.urls', namespace='pricelist')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    is_normal_user = models.BooleanField(default=False)
    is_employer = models.BooleanField(default=False)

    def __str__(self):
        return self.username

accounts/forms.py
from accounts.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.db import transaction


class SignUp(UserCreationForm):
    username = forms.CharField(label='', max_length=254, required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'username'}))
    email = forms.CharField(label='', max_length=254, required=True,
                            widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    password1 = forms.CharField(label='', max_length=254, required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(label='', max_length=254, required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Repeat Password'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'username',
            'email',
            'password1',
            'password2',
            Submit('submit', 'Signup', css_class='btn btn-filled btn-log margin-right'),
        )


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(label='', max_length=254, required=False,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name '}))
    last_name = forms.CharField(label='', max_length=254, required=False,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    username = forms.CharField(label='', max_length=254, required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'username'}))
    email = forms.CharField(label='', max_length=254, required=True,
                            widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    password1 = forms.CharField(label='', max_length=254, required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(label='', max_length=254, required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Repeat Password'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('first_name', css_class='mt-10 form-group col-md-6 col-sm-12 mb-0'),
                Column('last_name', css_class='mt-10 form-group col-md-6 col-sm-12 mb-0'),
                css_class='form-row'
            ),
            'username',
            'email',
            Row(
                Column('password1', css_class='mt-10 form-group col-md-6 col-sm-12 mb-0'),
                Column('password2', css_class='mt-10 form-group col-md-6 col-sm-12 mb-0'),
                css_class='form-row'
            ),
            Submit('submit', 'Signup', css_class='btn btn-filled btn-log margin-right'),
        )
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_normal_user = True
        user.save()
        return user


class EmployerSignUpForm(SignUp):
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_employer = True
        if commit:
            user.save()
        return user


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='', max_length=254, required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'username'}))
    password = forms.CharField(label='', max_length=254, required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'username',
            'password',
            Submit('submit', 'Login', css_class='btn btn-filled btn-log margin-right'),  # <i class="fa fa-sign-in"></i>

        )

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
# from django.core.checks import messages
from django.http import JsonResponse
from django.shortcuts import redirect
from django.views.generic import CreateView, TemplateView, UpdateView

# from .filters import UserFilter
from .forms import SignUpForm, EmployerSignUpForm, LoginForm
from .models import User


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


class NormalSignUpView(CreateView):
    model = User
    form_class = SignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'normal_user'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('dashboard')


class EmployerSignUpView(CreateView):
    model = User
    form_class = EmployerSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'employer'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('dashboard')


def validate_email(request):
    email = request.GET.get('email', None)
    data = {
        'is_taken': User.objects.filter(email__iexact=email).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'This email is already taken.'
    return JsonResponse(data)


def validate_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'A user with this username already exists.'
    return JsonResponse(data)


class UserLogin(LoginView):
    model = User
    form_class = LoginForm
    template_name = 'accounts/login.html'
    success_url = '/dashboard/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Login"
        return context


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ('first_name', 'last_name', 'email',)
    template_name = 'accounts/my_account.html'
    success_url = '/dashboard/'

    def get_object(self):
        return self.request.user

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load pinax_messages_tags %}
{% block title %} Dashboard | {{ block.super }} {% endblock %}
{% block lead %}
Welcome to you Dashboard{% endblock %}
{% block jumbotron %}
<a class="btn btn-common breadcrumb-item active">
  {% if user.is_employer %}
  You have signup as an Employer
  {% else %}
  You have signup as a non Employer
  {% endif %}
</a>

{% endblock  %}
{% block content %}
<div class="container">
  <div class="row">
    <!-- Tab panes -->
    <div class="col-md-4 col-sm-12">
      <div class="tab-content">
        <h4> Dashboard </h4>
        <hr/>
        <h6 class="text-muted">{{ user.get_full_name }}</h6>
        <br/>
        <ul>
          {% with user|unread_thread_count as user_unread %}
          <li class="{% if user_unread %} unread {% endif %}">
            <a href="{% url 'pinax_messages:inbox' %}"><i class="fa fa-envelope"></i> Messages
            {% if user_unread %}<sup>{{ user_unread }}</sup>{% endif %}
            </a>
          </li>
          {% endwith %}
          <br/>
          <li class="text-muted">
            <a href="{% url 'accounts:account_edit' %}">My account</a>
          </li>
          {% if user.is_normal_user %}
          <li class="text-muted">
            <a href='{% url "resume:new" %}'>Add Resume</a>
          </li>
          {% endif %}
          <hr/>
          {% if user.is_employer %}
          <li class="text-muted">
            <a href='{% url "company:new" %}'>Add Company</a>
          </li>
          <li class="text-muted">
            <a href='{% url "company:list" %}'>Add Jobs</a>
          </li>
          {% endif %}
          <li class="text-muted">
            <a href='{% url "company:list" %}'>Add Reviews</a>
          </li>
          <hr/>
          <li class="text-muted">
            <a href="{% url 'accounts:password_change' %}">Change Password</a>
          </li>
          <li class="text-muted">
            <a href="{% url 'accounts:logout' %}">Sign Out</a>
          </li>
        </ul>
      </div>
      <br/>
      <div class="tab-content">
        <h4> Other </h4>
        <hr/>
        <ul>
          <li class="text-muted">
            <a href="{% url 'category:list' %}">Categories</a>
          </li>
          <li class="text-muted">
            <a href='{% url "category:new" %}'>Add New Category</a>
          </li>
          <hr/>
          <li class="text-muted">
            <a href='{% url "location:list" %}'>Locations</a>
          </li>
          <li class="text-muted">
            <a href='{% url "location:new" %}'>Add New Location</a>
          </li>
          <li class="text-muted">
            <a href='{% url "country:list" %}'>Countries</a>
          </li>
        </ul>
      </div>

    </div>
    <!-- Tab panes -->

    <!-- Tab panes -->
    <div class="col-md-8 col-sm-12">
      <div class="tab-content">
        {% if user.is_normal_user %}
        <div class="sub-title">
          <span>My Resumes</span>
        </div>
        <div class="row card-body">
          <div class="col-sm-12 tab-content  ">
            <div class="row">
              <div class="col-md-2 col-sm-12 ">
                <a href="#" class="pull-left ">
                  <img class="img-fluid d-block w-100" src='{{ user.profile.thumbnail.url }}' alt="">
                </a>
              </div>
              <div class="col-md-10 col-sm-12">
                <h4 class="title">
                  <a href="{{user.profile.get_absolute_url }}">
                    {{ user.get_full_name }}
                  </a>
                </h4>
                <h6 class="text-muted">{{ user.profile.title }}</h6>
                <br/>
                <span>{{ user.profile.location.name }}</span>,
                <span>{{ user.profile.location.country.name }}</span>
                <span>{{ user.email }}</span>
                <div class="pull-right"> Published: {{ user.profile.publish }}</div>
                <br/>
                <hr/>
                <a href="{{user.profile.get_absolute_url }}" type="button"
                   class="btn std-btn btn-sm btn-filled pull-right">
                  Details
                </a>
                <a href="{{user.profile.get_absolute_url }}" type="button"
                   class="btn std-btn btn-sm btn-warning-filled pull-right">
                  Edit
                </a>
                <a href="{{user.profile.get_absolute_url }}" type="button"
                   class="btn std-btn btn-sm btn-danger-filled pull-right">
                  Delete
                </a>
              </div>
            </div>
          </div>


        </div>
        {% endif %}
        {% if user.is_employer %}
        <div class="mb-60">&nbsp;</div>
        <div class="sub-title">
          <span>My Companies</span>
        </div>
        {% if user.company_set %}
        {% for obj in user.company_set.all %}
        <div class="col-sm-12 tab-content  ">
          <div class="card-body">
            <div class="row">
              <div class="col-md-3 col-sm-12">
                {% if obj.logo %}
                <a href="{{ obj.get_absolute_url }}">
                  <img class="d-block w-100" src='{{ obj.logo.url }}'/>
                </a>
                {% else %}
                <a href="{{ obj.get_absolute_url }}">
                  <img class="d-block w-100" src='{% static "img/avatar.svg" %}'>
                </a>s
                {% endif %}
              </div>
              <div class="pull-right col-md-9 col-sm-12">
                <div class="col-md-12 post-header-line">
                  <h4 class="card-title">
                    <a href="{{ obj.get_absolute_url }}">
                      {{ obj.name }}
                    </a>
                    <span class="badge badge-primary">{{ obj.category.name }}</span>
                  </h4>{% if obj.website %}
                  <h6 class="card-subtitle mb-2 text-muted"><a href="{{ obj.website}}"> Website </a></h6>
                  {% endif %}
                  <p class="card-text">{{ obj.description|truncatechars:100 }}...</p>
                  <hr/>
                  <span><i class="fas fa-star"></i>{{ obj.average_rating | floatformat }} rating </span> |
                  <span><i class="fas fa-comments"></i>{{ obj.review_set.count }} reviews</span> |
                  {% if obj.location %}
                  <span><i
                          class="fas fa-map-marker-alt"></i>{{ obj.location.name }} | {{ obj.location.country.name }}</span>
                  {% endif %}
                  <div class="pull-right">
                    <a class="card-link" href="{{ obj.get_absolute_url }}">
                      <button type="button" class="btn btn-primary">Details</button>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <br/>
        {% endfor %}
        {% endif %}
        <div class="mb-60">&nbsp;</div>
        <div class="sub-title">
          <span>My Jobs </span>
        </div>
        {% if user.job %}
        <div class="table-responsive mtb">
          <table class="table table-bordered table-2 table-striped">
            <thead>
            <tr>
              <th>Title</th>
              <th>Company</th>
              <th>Openings</th>
              <th>Date</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in user.job.all %}
            <tr>
              <td><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></td>
              <td>{{ obj.company.name }}</td>
              <td> {{ obj.opening }} Opening{{ obj.opening|pluralize }}</td>
              <td>{{ obj.publish|timesince }} ago</td>
            </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        {% endif %}
        {% endif %}
        <div class="mb-60">&nbsp;</div>


      </div>
    </div>
  </div>
  <!-- Tab panes -->
</div>
</div>

<div class="mb-60">&nbsp;</div>


{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block title %} Login  | {{ block.super }} {% endblock %}
{% block breadcrumb %}
{% endblock  %}


{% block content %}
{% if form.non_field_errors %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  {% for error in form.non_field_errors %}
  <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
  {% endfor %}
  <button aria-label="Close" class="close" data-dismiss="alert" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}
<div class="mb-60"></div>
<div class="header-style-3">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 ">
        <h3 class="header-title animated fadeInDown text-white"><span class="text-primary">Job-Cycle </span>
          - Sign up for More Features
        </h3>

        <ol class="unorderedlist ">
          <li class="text-white">
            As a non employer add CV
          </li>
          <li class="text-white">
            Review companies as satisfied
          </li>
          <li class="text-white">
            As employer add Companies
          </li>
          <li class="text-white">
            Add Job Vacancies
          </li>
        </ol>
        <div class="modal-body">
          <a href="{% url 'accounts:normal_user_signup' %}" class="btn btn-success btn-lg" role="button">I'm not
            employer</a>
          <a href="{% url 'accounts:employer_signup' %}" class="btn btn-warning btn-lg" role="button">I'm an
            employer</a>
          <hr/>
          <div>

          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div id="login-form">
          <h3 class="log-title">Log In</h3>
          <div class="form-group">
            <form class="login-form" method='POST' action='' enctype='multipart/form-data' novalidate>
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ next }}">
              {% crispy form %}
            </form>
            <div class="clearfix"></div>
          </div>
          <a href="{% url 'accounts:password_reset' %}" class="forgot-password">Forgot your Password?</a>
        </div>
        <div class="mb-60"></div>
      </div>
    </div>
  </div>
</div>
<div class="mb-60"></div>
{% endblock content %}

templates/accounts/my_account.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}


<title>{% block title %}  My Account  | {{ block.super }} {% endblock %}</title>
{% block lead %}
My Account 
 {% endblock %}
{% block jumbotron %}
      <li class="breadcrumb-item active">My Account</li>
{% endblock  %}


{% block content %}

<section id="content">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-9 col-md-offset-2">
        <div class="page-ads box">
          <form enctype="multipart/form-data" class="form-ad" action="." method="POST">
            <div class="form-group is-empty">
              {% csrf_token %}
              {% crispy form %}
              <button type="submit" class="btn btn-success">Save changes</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/accounts/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}


<title>{% block title %}  Password Change   | {{ block.super }} {% endblock %}</title>
{% block lead %}
Password Change
 {% endblock %}
{% block jumbotron %}
      <li class="breadcrumb-item active">Password Change </li>
{% endblock  %}


{% block content %}
<!--banner-->
<div class="jumbotron">
  <div class=" mx-auto">
    <h5 class="lead"><strong> My Account </strong></h5>
    <hr class="my-4">
    <ol class="breadcrumb ">
      <li class="breadcrumb-item"><a href='{% url "home" %}'><i class="fas fa-home"></i>Home</a></li>
      <li class="breadcrumb-item active"> My Account</li>
    </ol>
  </div>
</div>
<!--endbanner-->

<section id="content">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-9 col-md-offset-2">
        <div class="page-ads box">
          <form enctype="multipart/form-data" class="form-ad" action="." method="POST">
            <div class="form-group is-empty">
              {% csrf_token %}
              {% crispy form %}
        <button type="submit" class="btn btn-success">Change password</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/accounts/password_change_done.html
{% extends 'base.html' %}

{% block title %}Change password successful{% endblock %}


{% block lead %}
Password Change Done 
 {% endblock %}
{% block jumbotron %}
  <li class="breadcrumb-item"><a href="{% url 'accounts:password_change' %}">Change password</a></li>
  <li class="breadcrumb-item active">Success</li>
{% endblock  %}



{% block content %}
  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'category:list' %}" class="btn btn-secondary">Return to home page</a>
{% endblock %}

templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}  Reset your password  | {{ block.super }} {% endblock %}
{% block lead %}
 {{ company.name }} 
 {% endblock %}
{% block jumbotron %}
      <li class="breadcrumb-item active">Reset your password</li>
{% endblock  %}

{% block content %}


  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}

{% block lead %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
 {% endblock %}
{% block jumbotron %}
        {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock  %}


{% block content %}
<!--banner-->
<div class="jumbotron">
  <div class=" mx-auto">
    <h5 class="lead"><strong> Reset your password </strong></h5>
    <hr class="my-4">
    <ol class="breadcrumb ">
      <li class="breadcrumb-item"><a href='{% url "home" %}'><i class="fas fa-home"></i>Home</a></li>
      <li class="breadcrumb-item active">Reset your password</li>
    </ol>
  </div>
</div>
<!--endbanner-->

  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'accounts:password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}


<title>{% block title %}  Reset your password  | {{ block.super }} {% endblock %}</title>
{% block lead %}
Reset your password 
 {% endblock %}
{% block jumbotron %}
      <li class="breadcrumb-item active">Reset your password</li>
{% endblock  %}


{% block content %}

<div class="row justify-content-center">
  <div class="col-lg-4 col-md-6 col-sm-8">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Reset your password</h3>
        <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your
          spam folder.</p>
        <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}. Follow the link below:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead.

If you've received this mail in error, it's likely that another user entered your email address by mistake while trying
to reset a password. If you didn't initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Django Boards Team