job/urls.py
from django.urls import path

from .views import JobEdit, JobDelete, JobDetail, job_list_view

app_name = 'job'

urlpatterns = [
    # path('new/', JobCreate.as_view(), name='new'),
    # path('<slug:slug>/edit/', JobEdit.as_view(), name='edit'),
    path('<slug:slug>delete/', JobDelete.as_view(), name='delete'),
    path('<slug:slug>/', JobDetail.as_view(), name='detail'),
    # path('', JobList.as_view(), name='list'),
    path('', job_list_view, name='list'),

]

jobcorner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.flatpages.views import flatpage
from django.urls import path, include
from django_filters.views import FilterView

from homepage.views import HomeIndex, UserFilter, Dashboard

urlpatterns = [
    path('dashboard', Dashboard.as_view(), name='dashboard'),
    path('', HomeIndex.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('company/', include('company.urls', namespace='company')),
    path('category/', include('category.urls', namespace='category')),
    path('country/', include('country.urls', namespace='country')),
    path('location/', include('location.urls', namespace='location')),
    path('job/', include('job.urls', namespace='job')),
    path('resume/', include('resume.urls', namespace='resume')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('search/', FilterView.as_view(filterset_class=UserFilter, template_name='search.html'), name='search'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',
                                                        email_template_name='accounts/password_reset_email.html',
                                                        subject_template_name='accounts/password_reset_subject.txt'),
         name='password_reset'),
    path("likes/", include("pinax.likes.urls", namespace="pinax_likes")),
    path('notifications/', include("pinax.notifications.urls", namespace="notifications")),
    path('messages/', include("pinax.messages.urls", namespace="pinax_messages")),

    path('about-us/', flatpage, {'url': '/about-us/'}, name='about'),
    path('license/', flatpage, {'url': '/license/'}, name='license'),
    path('terms/', flatpage, {'url': '/terms/'}, name='terms'),
    path('pricelist/', include('pricelist.urls', namespace='pricelist')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/urls.py
from django.urls import path

from .views import ProfileCreateView, ProfileList, ProfileDelete, ProfileDetail, EducationCreate, ExperienceCreate, \
    CVPdfDetailView, SkillsCreate

app_name = 'resume'

urlpatterns = [
    path('new/', ProfileCreateView.as_view(), name='new'),
    path('<slug>/', ProfileDetail.as_view(), name='detail'),
    path('<slug>/delete/', ProfileDelete.as_view(), name='delete'),
    path('<slug>/education/new/', EducationCreate.as_view(), name='new_education', ),
    path('<slug>/experience/new/', ExperienceCreate.as_view(), name='new_experience', ),
    path('<slug>/skills/new/', SkillsCreate.as_view(), name='new_skills'),
    path('<slug>/pdf/', CVPdfDetailView.as_view(), name='pdf'),
    path('', ProfileList.as_view(), name='list'),

]

resume/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from taggit.managers import TaggableManager
from taggit.models import TaggedItemBase

from accounts.models import User
from blog.models import STATUS_CHOICES
from location.models import Location


class TaggedProfile(TaggedItemBase):
    content_object = models.ForeignKey('Profile', on_delete=models.PROTECT)


class PublishedManager(models.Manager):

    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='profile')
    title = models.CharField(max_length=100, blank=True)
    slug = models.SlugField(max_length=200, blank=True, null=True, unique=True)
    bio = models.TextField(max_length=500, blank=True)
    location = models.ForeignKey(Location, related_name='profile', blank=True, null=True, on_delete=models.PROTECT)
    birth_date = models.DateField(null=True, blank=True)
    thumbnail = models.ImageField(upload_to="users/thumbnail", blank=True, null=True)
    phone = models.IntegerField(blank=True, null=True)
    website = models.URLField(max_length=300, blank=True, null=True)
    facebook = models.CharField(max_length=100, blank=True)
    instagram = models.CharField(max_length=100, blank=True)
    twitter = models.CharField(max_length=100, blank=True)
    linkedin = models.CharField(max_length=100, blank=True)
    google = models.CharField(max_length=100, blank=True)
    pinterest = models.CharField(max_length=100, blank=True)

    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")
    tags = TaggableManager(through=TaggedProfile)

    publish = models.DateTimeField('date published', auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    objects = models.Manager()
    published = PublishedManager()

    def save(self, *args, **kwargs):
        slug = slugify(self.user.username)
        self.slug = slug
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('resume:detail', kwargs={"slug": self.slug})


SKILL_LEVELS = (
    (None, 'unknown'),
    ('B', 'beginner'),
    ('S', 'skilled'),
    ('A', 'advanced'),
    ('E', 'expert'),
)


class Skill(models.Model):
    profile = models.ForeignKey(Profile, related_name="skills", on_delete=models.CASCADE)
    name = models.CharField(max_length=200, unique=True, verbose_name="name")
    description = models.TextField(max_length=2000, blank=True)
    level = models.CharField(max_length=1, choices=SKILL_LEVELS, verbose_name="level")
    tags = TaggableManager()

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('resume:detail', kwargs={"slug": self.profile.slug})


class Experience(models.Model):
    profile = models.ForeignKey(Profile, related_name='experience', on_delete=models.CASCADE)
    role = models.CharField(max_length=150)
    company = models.CharField(max_length=150)
    company_url = models.URLField('Company URL')
    start_date = models.DateField(null=True, blank=True, verbose_name="start date")
    completion_date = models.DateField(null=True, blank=True, verbose_name="end date")
    description = models.TextField(verbose_name="description")
    is_current = models.BooleanField(default=True, verbose_name="still in office")

    class Meta:
        ordering = ['-completion_date', '-start_date']

    def clean(self):
        if self.start_date and self.completion_date:
            if self.start_date > self.completion_date:
                raise ValidationError({"start_date": ("Start date must be "
                                                      "before end date."),
                                       "completion_date": ("Start date must be "
                                                           "before end date.")})

    def get_absolute_url(self):
        return reverse('resume:detail', kwargs={"slug": self.profile.slug})


class Education(models.Model):
    profile = models.ForeignKey(Profile, related_name='education', on_delete=models.CASCADE)
    school = models.CharField(max_length=150, verbose_name="school")
    school_url = models.URLField('School URL')
    major = models.CharField(max_length=50, blank=True, )
    result = models.CharField(max_length=150, blank=True, verbose_name="result")
    start_date = models.DateField(null=True, blank=True, verbose_name="start date")
    completion_date = models.DateField(null=True, blank=True, verbose_name="end date")
    summary = models.TextField(max_length=3000, blank=True, verbose_name="Summary description")
    is_current = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Education"

    def __str__(self):
        return self.major

    def clean(self):
        if self.start_date and self.completion_date:
            if self.start_date > self.completion_date:
                raise ValidationError({"start_date": ("Start date must be "
                                                      "before end date."),
                                       "completion_date": ("Start date must be "
                                                           "before end date.")})

    def get_absolute_url(self):
        return reverse('resume:detail', kwargs={"slug": self.profile.slug})

resume/views.py
from django.contrib.auth.mixins import LoginRequiredMixin

from accounts.decorators import normal_user_required
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView
from django.views.generic.edit import DeleteView, CreateView
from django_xhtml2pdf.utils import render_to_pdf_response

from .forms import ProfileForm, SkillForm, ExperienceForm, EducationForm
from .models import Profile, Skill, Experience, Education


class ProfileList(ListView):
    queryset = Profile.published.all()
    context_object_name = 'profile'
    template_name = 'resume/list.html'
    paginate_by = 6


class ProfileDetail(DetailView):
    queryset = Profile.published.all()
    context_object_name = 'profile'
    template_name = 'resume/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['skill_list'] = Skill.objects.filter(profile=self.get_object())
        context['education_list'] = Education.objects.filter(profile=self.get_object())
        context['experience_list'] = Experience.objects.filter(profile=self.get_object())
        return context


@method_decorator([login_required, normal_user_required], name='dispatch')
class ProfileDelete(DeleteView):
    model = Profile
    success_url = reverse_lazy('profile:list')
    context_object_name = 'profile'
    template_name = 'resume/delete.html'


class ProfileCreate(LoginRequiredMixin, CreateView):
    template_name = 'form.html'

    def form_valid(self, form):
        form.instance.profile = get_object_or_404(Profile, slug=self.kwargs['slug'])
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        """
        If the form is invalid, re-render the context data with the
        data-filled form and errors.
        """
        print('the is an error in your form')
        messages.warning(self.request, 'There was an error in this form')
        return self.render_to_response(self.get_context_data(form=form))


class SkillsCreate(ProfileCreate):
    model = Skill
    form_class = SkillForm


class ExperienceCreate(ProfileCreate):
    model = Experience
    form_class = ExperienceForm


class EducationCreate(ProfileCreate):
    model = Education
    form_class = EducationForm

@method_decorator([login_required, normal_user_required], name='dispatch')
class ProfileCreateView(CreateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        """
        If the form is invalid, re-render the context data with the
        data-filled form and errors.
        """
        print('there is an error in your form')
        messages.warning(self.request, 'There was an error in this form')
        return self.render_to_response(self.get_context_data(form=form))


class PdfResponseMixin(object, ):
    pdf_name = "output"

    def get_pdf_name(self):
        return self.pdf_name

    def render_to_response(self, context, **response_kwargs):
        context = self.get_context_data()
        template = self.get_template_names()[0]
        resp = HttpResponse(content_type='application/pdf')
        resp['Content-Disposition'] = 'attachment; filename="{0}.pdf"'.format(self.get_pdf_name())
        result = render_to_pdf_response(template, context=context)
        return result


class CVPdfDetailView(PdfResponseMixin, DetailView):
    context_object_name = 'profile'
    # slug_field = "username"
    model = Profile
    template_name = 'resume/cv/cv_pdf.html'

templates/resume/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load pinax_likes_tags %}
{% load activity_tags %}

{% block title %} {{ profile.user.username }}'s Profile  | {{ block.super }} {% endblock %}
{% block breadcrumb %}
{% endblock  %}
{% block content %}
<!-- Headers Start -->

<div id="headers">
  <!-- Light header -->
  <header id="header-style-1">
    <div class="container">
      <div class="header-caption">
        <div class="row">
          <div class="col-md-12 col-sm-12 text-center header-content">
            <div class="contents">
              <h5 class="header-title animated fadeInUp" data-wow-delay="0.2s">Hi This is</h5>
              <h2 class="header-title animated fadeInUp" data-wow-delay="0.4s">{{ profile.user.get_full_name }}</h2>
              <p class="header-text animated  fadeInUp" data-wow-delay="0.6s">{{ profile.title }}</p>
              <div class="social-icon col-md-12 col-sm-12 mx-auto">
                {% if profile.facebook %}
                <a href="{{ profile.facebook }}"><i class="fa fa-facebook"></i></a>
                {% endif %}
                {% if profile.twitter %}
                <a href="{{ profile.twitter }}"><i class="fa fa-twitter"></i></a>
                {% endif %}
                {% if profile.google %}
                <a href="{{ profile.google }}"><i class="fa fa-google-plus"></i></a>
                {% endif %}
                {% if profile.pinterest %}
                <a href="{{ profile.pinterest }}"><i class="fa fa-pinterest"></i></a>
                {% endif %}
                {% if profile.linkedin %}
                <a href="{{ profile.linkedin }}"><i class="fa fa-linkedin"></i></a>
                {% endif %}
              </div>&nbsp;
              <div class="header-button wow fadeInUp" data-wow-delay="1s">
                <a class="btn btn-common" href="#">Hire Me</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
</div>
<!-- Headers End -->
  <hr/>
  <a href="{% follow_url other_user %}">
    {% if request.user|is_following:another_user %}
    You are already following {{ another_user }}
    {% endif %}


    {% if request.user|is_following:other_user %}
    stop following
    {% else %}
    follow
    {% endif %}
  </a>


<a href="{% actor_url request.user %}">View your actions</a>
<a href="{% actor_url another_user %}">{{ another_user }}'s actions</a>
  <hr/>
{% if profile %}
<!--simple card 10-->
<div class="container">
  <div class="card mx-auto col-md-12 mb-2 ">
    <div class="card-body">
      <div class="row">
        <div class="col-md-3 col-sm-12">
          {% if profile.thumbnail %}
          <img class="img-fluid" src='{{ profile.thumbnail.url }}' alt="">
          {% endif %}
        </div>
        <div class="pull-right col-md-9 col-sm-12">
          <div class="card-title">
            <strong>{{ profile.user.get_full_name }}</strong>
          </div>
          <div class="card-subtitle">
            {{ profile.title }}
          </div>
          <p>
            {{ profile.location }}, {{ profile.location.country.name }}
          </p>
          <p>
            {{ profile.user.email }}, {{ profile.phone }}
          </p>
          <a href='{% url "resume:pdf" profile.slug %}' class="btn btn-common"><i class="icon-paper-clip"></i>
            Download Resume
          </a>
          {% if profile.user == request.user %}
          <a href='' class="btn btn-danger"><i class="icon-speech"></i> Edit Resume </a>
          {% endif %}
          {% else %}
          <a href='{% url "resume:new" %}' type="button" class="btn btn-success btn-lg">
            Add Resume
          </a>
        </div>
        {% endif %}
        <hr/>
        <div class="col-md-12">
          <h2 class="card-title">
            About Me
          </h2>
          <p class="text-muted">
            {{ profile.bio }}
          </p>
          <hr/>

          {% if profile.user == request.user %}
          <div class="pull-right">
            <a href='{% url "resume:new_skills" profile.slug %}' type="button"
               class="btn std-btn btn-sm btn-filled">
              Add Skills
            </a>
          </div>
          {% endif %}
          {% for obj in profile.skills.all %}
          <h2 class="card-title">
            Skills
          </h2>
          <h5 class="card-title">
            {{ obj.name }}
          </h5>
          <h6 class="card-subtitle">
            {{ obj.get_level_display }}
          </h6>
          <p class="text-muted">
            {{ obj.description }}
          </p>
          {% if profile.user == request.user %}
          <a href='' class="btn btn-danger btn-sm"><i class="icon-speech"></i> Edit </a>
          {% endif %}
          {% endfor %}
          <hr/>

          <h2 class="card-title">
            Experience
          </h2>
          {% if profile.user == request.user %}
          <div class="pull-right">
            <a href='{% url "resume:new_experience" profile.slug %}' type="button"
               class="btn std-btn btn-sm btn-filled">
              Add Experience
            </a>
          </div>
          {% endif %}
          {% for obj in profile.experience.all %}
          <h4>
            {{ obj.role }} - {{ obj.company }}
          </h4>
          <span> {{ obj.start_date }}- {{ obj.completion_date }} </span>
          <p class="text-muted">
            {{ obj.description }}
          </p>
          {% if profile.user == request.user %}
          <a href='' class="btn btn-sm btn-danger"><i class="icon-speech"></i> Edit </a>
          {% endif %}
          {% endfor %}
          <hr/>

          <h2 class="card-title">
            Education
          </h2>
          <div class="pull-right">
            {% if profile.user == request.user %}
            <a href='{% url "resume:new_education" profile.slug %}' type="button"
               class="btn std-btn btn-sm btn-filled">
              Add Education
            </a>
          </div>
          {% endif %}
          {% for obj in profile.education.all %}
          <h4>
            {{ obj.major }} - {{ obj.school }}
          </h4>
          <span> {{ obj.start_date }}- {{ obj.completion_date }} </span>
          <p class="text-muted">
            {{ obj.summary }}
          </p>
          {% if profile.user == request.user %}
          <a href='' class="btn btn-sm btn-danger"><i class="icon-speech"></i> Edit </a>
          {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<!--end of simple card 10-->
<div class="mb-60"></div>
{% endblock %}

templates/resume/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}  {{ title }}  | {{ block.super }} {% endblock %}
{% block lead %}
{{ title }} 
 {% endblock %}
{% block jumbotron %}
      <li class="breadcrumb-item active">{{ title }}</li>
{% endblock  %}


{% block content %}

<section id="content">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-9 col-md-offset-2">
        <div class="page-ads box">
          <form enctype="multipart/form-data" class="form-ad" action="." method="POST">
            <div class="form-group is-empty">
              {% csrf_token %}
              {{ form|crispy }}
              <fieldset>
                <div class="divider"><h3>Photos</h3></div>
                {% for form in inlines %}
                {{ form|crispy }}
                {% endfor %}
              </fieldset>
              <button class="btn btn-success">Submit</button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/resume/latest_profile.html
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="page-header-title">
        <h2 class="heading-title text-center">Latest Resumes</h2>
      </div>
    </div>
    {% for obj in latest_profile %}
    <div class="col-md-4">
      <div class="card-2">
        <div class="image">
           <img class="img-fluid" src='{{ obj.thumbnail.url }}' alt="">
        </div>
        <div class="card-block">
          <h3 class="card-title"><a href="{{ obj.get_absolute_url }}">{{ obj.user.get_full_name }}</a></h3>
          <div class="meta">
            <a>{{ obj.title }}</a>
          </div>
          <div class="description">
            {{ obj.bio|truncatechars:100 }}
          </div>
        </div>
        <div class="extra">
                <span class="right">
                  Joined in {{ obj.publish }}
                </span>&nbsp;
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

templates/resume/list.html
{% extends 'base.html' %}
{% load accounts_tags %}
{% load staticfiles %}
{% load widget_tweaks %}


{% block title %} Profile List | {{ block.super }} {% endblock %}
{% block lead %}
Profile/Resume list
{% endblock %}
{% block jumbotron %}
        <a class="btn btn-common breadcrumb-item active">
          Profile/Resume list
        </a>
        <a class="btn btn-common" href='{% url "resume:new" %}'>
          new
        </a>
{% endblock  %}

{% block content %}


<!--table list-->
<div class="container">
  {% if profile %}
  {% for obj in profile %}
  <div class="card col-md-10">
    <div class="row card-body">
      <div class="col-md-2 ">
        <a href="#" class="pull-left ">
          <img class="img-fluid d-block w-100" src='{{ obj.thumbnail.url }}' alt="">
        </a>
      </div>
      <div class="col-md-10">
        <h4 class="title">
          <a href="{{ obj.get_absolute_url }}">
          {{ obj.user.get_full_name }}
          </a>
        </h4>
        <span>
                <p class="summary"> {{ obj.bio|truncatechars:100  }}...</p></span>
        <div>
          <hr/>
          <a href="{{ obj.get_absolute_url }}" class="card-link btn btn-primary pull-right">Details</a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  {% else %}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">currently no Profile</h5>
      </div>
      <div class="modal-body">
        <a href="{% url 'resume:new' %}" class="btn btn-success btn-lg" role="button">Add Profile</a>
      </div>
    </div>
  </div>
  {% endif %}
</div>
<!--end table list-->
{% endblock %}