blog/urls.py
from django.urls import path

from .views import PostCreate, PostDetail, PostEdit, PostDelete, PostList, add_comment

app_name = 'Post'

urlpatterns = [
    path('new/', PostCreate.as_view(), name='new'),
    path('<slug:slug>/', PostDetail.as_view(), name='detail'),
    path('<slug:slug>/edit/', PostEdit.as_view(), name='edit'),
    path('<slug:slug>/delete/', PostDelete.as_view(), name='delete'),

    path('', PostList.as_view(), name='list'),
    path('<post_id>/add_comment/', add_comment, name='add_comment'),

]

job/urls.py
from django.urls import path

from .views import JobEdit, JobDelete, JobDetail, job_list_view

app_name = 'job'

urlpatterns = [
    # path('new/', JobCreate.as_view(), name='new'),
    # path('<slug:slug>/edit/', JobEdit.as_view(), name='edit'),
    path('<slug:slug>delete/', JobDelete.as_view(), name='delete'),
    path('<slug:slug>/', JobDetail.as_view(), name='detail'),
    # path('', JobList.as_view(), name='list'),
    path('', job_list_view, name='list'),

]

jobcorner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.flatpages.views import flatpage
from django.urls import path, include
from django_filters.views import FilterView

from homepage.views import HomeIndex, UserFilter, Dashboard

urlpatterns = [
    path('dashboard', Dashboard.as_view(), name='dashboard'),
    path('', HomeIndex.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('company/', include('company.urls', namespace='company')),
    path('category/', include('category.urls', namespace='category')),
    path('country/', include('country.urls', namespace='country')),
    path('location/', include('location.urls', namespace='location')),
    path('job/', include('job.urls', namespace='job')),
    path('resume/', include('resume.urls', namespace='resume')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('search/', FilterView.as_view(filterset_class=UserFilter, template_name='search.html'), name='search'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',
                                                        email_template_name='accounts/password_reset_email.html',
                                                        subject_template_name='accounts/password_reset_subject.txt'),
         name='password_reset'),
    path("likes/", include("pinax.likes.urls", namespace="pinax_likes")),
    path('notifications/', include("pinax.notifications.urls", namespace="notifications")),
    path('messages/', include("pinax.messages.urls", namespace="pinax_messages")),

    path('about-us/', flatpage, {'url': '/about-us/'}, name='about'),
    path('license/', flatpage, {'url': '/license/'}, name='license'),
    path('terms/', flatpage, {'url': '/terms/'}, name='terms'),
    path('pricelist/', include('pricelist.urls', namespace='pricelist')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pricelist/urls.py
from django.urls import path

from . import views

app_name = 'pricelist'

urlpatterns = [
    path('<slug:slug>/', views.DetailView.as_view(), name='detail'),
    path('<slug:slug>/results/', views.ResultsView.as_view(), name='edit'),

    path('', views.ListView.as_view(), name='list'),
    path('<service_id>/add_price/', views.add_price, name='add_price'),

]

templates/prices/detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load staticfiles %}
{% load social_share %}

{% block title %}  {{ service.name }}  | {{ block.super }} {% endblock %}
{% block lead %}
{{ service.name }}
{% endblock %}
{% block jumbotron %}
<a class="btn btn-common" href='{% url "pricelist:list" %}'>Price List
</a>
<a class="btn btn-common active">{{ service.name }}
</a>
{% endblock  %}


{% block content %}
<div class="container">
  <div class="card clearfix">
    <div class="card-body">
      <div class="mb-60"></div>
      <h3 class="text-center">
        Price of {{ service.name }} {{ service.type }} {{ service.item }} in {{ service.location }}
      </h3>
      <div class="mb-60"></div>
      <div class="col-md-12 text-center">
        <p>{{ service.description | truncatechars:500 }}</p>
        <br/>
        <div class="pull-right ">
          <span class="text-mute">
            Asked by: {{ service.user }} |
            {{ service.publish | date }}
          </span>
        </div>
        <br/>
        <hr/>
      </div>
      <div class=" col-md-8">
        <div class="page-header-title text-center mx-auto">
          <h1>
            <span>Av Price</span>
            <span class=" pull-right text-right">Ksh: {{ service.average_price | floatformat }} </span></h1>
        </div>
      </div>
      <div class="pull-right">
        {% if service.service.count == 1 %}
        Offered by {{ service.service.count }} company
        {% else %}
        Offered by {{ service.service.count }} companies
        {% endif %}
        <h6>
          Share on
        </h6>
  <div class="social-footer row">
    <span>
    {% post_to_facebook object_or_url "<i class='fa fa-facebook icon-round'></i>" %}
    </span>
    <span>
    {% post_to_twitter "Price of: {{service.name}}. Check it out!" object_or_url "<i class='fa fa-twitter icon-round'></i>" %}
    </span>
    <span>
    {% post_to_linkedin object.title object_or_url "<i class='fa fa-linkedin icon-round'></i>" %}
    </span>
      <span>
    {% send_email object.title "Price of: {{service.name}}. Check it out!" object_or_url "<i class='fa fa-envelope icon-round'></i>" %}
    </span>
  </div>
      </div>
      <div class="mb-60"></div>
    </div>
  </div>

  <div class="row">
    <!--form-->
    <div class="col-md-12 mb-2">
      <div class="blog-block mx-auto">
        <div class="card-body">
          <h2>Add Your Price</h2>
          {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
          <form action="{% url 'pricelist:add_price' service.id %}" class="form-ad" enctype="multipart/form-data"
                method="post">
            <div class="form-group is-empty">
              {% csrf_token %}
              {% crispy form %}
            </div>
          </form>
        </div>
      </div>
    </div>
    <!--endform-->
    <div class="col-md-12 clearfix">
      {% if service.service %}
      {% for obj in service.service.all %}
      <div class="card mb-2">
        <div class="card-body ">
          <div class="row">
            <div class="col-md-3 col-sm-12">
              {% if obj.image %}
              <a href="">
                <img class="d-block w-100" src='{{ obj.image.url }}'/>
              </a>
              {% else %}
              <a href="">
                <img class="d-block w-100" src='{% static "img/avatar.svg" %}'>
              </a>
              {% endif %}
            </div>
            <div class="col-md-6 col-sm-12">
              <div class="col-md-12 post-header-line">
                <h4 class="card-title">
                  <a href="{{ obj.get_absolute_url }}">
                    {{ obj.company.name }}
                  </a>
                  <button class="label label-pill label-primary-filled">
                    KSH {{ obj.amount | floatformat }}
                  </button>
                </h4>
                {% if obj.company.website %}
                <h6 class="card-subtitle mb-2 text-muted"><a href="{{ obj.company.website}}"> Website </a></h6>
                {% endif %}
                <p class="card-text">{{ obj.description|truncatechars:250 }}</p>
              </div>
            </div>
            <div class="pull-right col-md-3 col-sm-12">
              <a class="btn btn-primary" href="{% url 'pinax_messages:message_user_create' user_id=object.user.id %}">
                <i class="fa fa-envelope"></i> Request a Quote
              </a>
              <hr/>
              <div>
                {{ obj.publish | date }}
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">No Price has been given yet</h5>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
    <div class="col-md-4 pull-right">
    </div>
  </div>
</div>
<div class="mb-60"></div>
{% endblock content %}

templates/prices/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}  Price List  | {{ block.super }} {% endblock %}
{% block lead %}
Price List
{% endblock %}
{% block jumbotron %}
<a class="btn btn-common breadcrumb-item active">
  Location List
</a>
<a class="btn btn-common" href='{% url "location:new" %}'>
  new
</a>
{% endblock  %}


{% block content %}
<div class="container">
  <div class="card">
    <div class="card-body">
      <h1 class="">Service Prices</h1>
      <br/>
      <div class="list-style">
        <div class="row">
          <div class="col-md-3">
            <p>SERVICE</p>
          </div>
          <div class="col-md-3">
            <p>ITEM</p>
          </div>
          <div class="col-md-3">
            <p>AV PRICE</p>
          </div>
          <div class="col-md-3">
            <p>ENTRIES</p>
          </div>
        </div>
      </div>
      <br/>
      <hr/>
      <br/>
      {% if service_list %}
      {% for obj in service_list %}
      <div class="alerts-content">
        <div class="row">
          <div class="col-md-3">
            <h4><a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a></h4>
            <span class="text-muted"><i class="ti-location-pin"></i> {{ obj.location }},  {{ obj.location.country.name }}</span>
          </div>
          <div class="col-md-3">
            <p>{{ obj.type }}</p>
          </div>
          <div class="col-md-3">
            <p><span class="label label-pill label-primary-filled">KSH {{ obj.average_price | floatformat }}</span></p>
          </div>
          <div class="col-md-3">
            <p class="text-muted">{{ obj.service.count }}</p>
          </div>
        </div>
      </div>
      <br/>
      <hr/>
      <br/>
      {% endfor %}
      {% else %}
      <p>No prices are available.</p>
      {% endif %}
      <div class="mb-60">&nbsp;</div>
    </div>

  </div>
</div>
{% endblock %}

templates/prices/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>

templates/prices/services.html
<div class="container">
  <div class="card">
    <div class="card-body">
      <h1 class="">What is the Price of?</h1>
      <br/>
      <div class="list-style">
        <div class="row">
          <div class="col-md-3">
            <p>SERVICE</p>
          </div>
          <div class="col-md-3">
            <p>ITEM</p>
          </div>
          <div class="col-md-3">
            <p>AV PRICE</p>
          </div>
          <div class="col-md-3">
            <p>ENTRIES</p>
          </div>
        </div>
      </div>
      <br/>
      <hr/>
      <br/>
      {% if services %}
      {% for obj in services %}
      <div class="alerts-content">
        <div class="row">
          <div class="col-md-3">
            <h4><a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a></h4>
            <span class="text-muted"><i class="ti-location-pin"></i> {{ obj.location }},  {{ obj.location.country.name }}</span>
          </div>
          <div class="col-md-3">
            <p>{{ obj.type }} {{ obj.item }}</p>
          </div>
          <div class="col-md-3">
            <p><span class="label label-pill label-primary-filled">KSH {{ obj.average_price | floatformat }}</span></p>
          </div>
          <div class="col-md-3">
            <p class="text-muted">{{ obj.service.count }}</p>
          </div>
        </div>
      </div>
      <br/>
      <hr/>
      <br/>
      {% endfor %}
      {% else %}
      <p>No prices are available.</p>
      {% endif %}

      <div class="pull-right">
        <a class="btn std-btn btn-sm btn-filled" href='{% url "pricelist:list" %}'
           type="button">
          More
        </a>
      </div>
      <div class="mb-60">&nbsp;</div>
    </div>

  </div>
</div>