job/urls.py
from django.urls import path

from .views import JobEdit, JobDelete, JobDetail, job_list_view

app_name = 'job'

urlpatterns = [
    # path('new/', JobCreate.as_view(), name='new'),
    # path('<slug:slug>/edit/', JobEdit.as_view(), name='edit'),
    path('<slug:slug>delete/', JobDelete.as_view(), name='delete'),
    path('<slug:slug>/', JobDetail.as_view(), name='detail'),
    # path('', JobList.as_view(), name='list'),
    path('', job_list_view, name='list'),

]

jobcorner/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.flatpages.views import flatpage
from django.urls import path, include
from django_filters.views import FilterView

from homepage.views import HomeIndex, UserFilter, Dashboard

urlpatterns = [
    path('dashboard', Dashboard.as_view(), name='dashboard'),
    path('', HomeIndex.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('company/', include('company.urls', namespace='company')),
    path('category/', include('category.urls', namespace='category')),
    path('country/', include('country.urls', namespace='country')),
    path('location/', include('location.urls', namespace='location')),
    path('job/', include('job.urls', namespace='job')),
    path('resume/', include('resume.urls', namespace='resume')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('search/', FilterView.as_view(filterset_class=UserFilter, template_name='search.html'), name='search'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',
                                                        email_template_name='accounts/password_reset_email.html',
                                                        subject_template_name='accounts/password_reset_subject.txt'),
         name='password_reset'),
    path("likes/", include("pinax.likes.urls", namespace="pinax_likes")),
    path('notifications/', include("pinax.notifications.urls", namespace="notifications")),
    path('messages/', include("pinax.messages.urls", namespace="pinax_messages")),

    path('about-us/', flatpage, {'url': '/about-us/'}, name='about'),
    path('license/', flatpage, {'url': '/license/'}, name='license'),
    path('terms/', flatpage, {'url': '/terms/'}, name='terms'),
    path('pricelist/', include('pricelist.urls', namespace='pricelist')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

location/urls.py
from django.urls import path

from .views import LocationCreate, LocationDetail, LocationList, LocationEdit, LocationDelete

app_name = 'location'

urlpatterns = [
    path('new/', LocationCreate.as_view(), name='new'),
    path('<slug:slug>/', LocationDetail.as_view(), name='detail'),
    path('<slug:slug>/edit', LocationEdit.as_view(), name='edit'),
    path('<slug:slug>/delete/', LocationDelete.as_view(), name='delete'),

    path('', LocationList.as_view(), name='list'),

]

location/models.py
from __future__ import unicode_literals

from builtins import super

from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from country.models import Country


class Location(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, blank=True, null=True)
    photo = models.ImageField(upload_to="address/location", blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    country = models.ForeignKey(Country, related_name='country', on_delete=models.CASCADE)

    publish = models.DateTimeField('date published', auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        verbose_name_plural = "locations"
        ordering = ['name']


    _metadata = {
        'title': 'name',
        'description': 'description',
    }

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        slug = slugify(self.name)
        self.slug = slug
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("location:detail", kwargs={"slug": self.slug})

location/forms.py
from builtins import super

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Row, Submit
from django import forms
from pagedown.widgets import PagedownWidget

from country.models import Country
from .models import Location


class LocationForm(forms.ModelForm):
    name = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'placeholder': 'Location Name'}))
    description = forms.CharField(label='', required=False, max_length=1024,
                                  widget=PagedownWidget(attrs={'placeholder': 'Description'}))
    country = forms.ModelChoiceField(label='', required=False, queryset=Country.objects.all(),
                                      empty_label="Choose Country")

    class Meta:
        model = Location
        fields = ('name', 'country', 'description')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('name', css_class='mt-10 form-group col-md-6 mb-0'),
                Column('country', css_class='mt-10 form-group col-md-6 mb-0'),
                css_class='form-row',
            ),
            'description',
            Submit('submit', 'Submit'),
        )

location/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView

from category.models import Category
from location.forms import LocationForm
from location.models import Location


class LocationCreate(LoginRequiredMixin, CreateView):
    model = Location
    form_class = LocationForm
    template_name = 'form.html'


class LocationEdit(LoginRequiredMixin, UpdateView):
    model = Location
    form_class = LocationForm
    template_name = 'form.html'


class LocationDelete(LoginRequiredMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('location_list')
    template_name = 'delete.html'


class LocationList(ListView):
    model = Location
    context_object_name = 'location'
    template_name = 'location/list.html'
    paginate_by = 12
    queryset = Location.objects.all()


class LocationDetail(DetailView):
    model = Location
    context_object_name = 'location'
    template_name = 'location/detail.html'

templates/location/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}  {{ location.name }}  | {{ block.super }} {% endblock %}
{% block lead %}
{{ location.name }}
{% endblock %}
{% block jumbotron %}
<a class="btn btn-common" href='{% url "location:list" %}'>Location List
</a>
<a class="btn btn-common active">{{ location.name }}
</a>
{% endblock  %}


{% block content %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">{{ location.name }}</h1>
    <p class="lead">{{ location.description }}</p>
    <hr/>
    <p>
      <i class="fas fa-user-tie"></i> <a> In {{ location.country.name }} </a> |
      <span><i class="far fa-calendar-alt"></i></span> added on {{ location.publish }}
    </p>
    <div class="pull-right">
      <a href='{% url "location:edit" location.slug %}' type="button" class="btn btn-primary pull-right">Update
      </a>
      <a href='{% url "location:delete" location.slug %}' type="button" class="btn btn-danger pull-right">Delete
      </a>
    </div>
  </div>
</div>


{% if location.company.all %}
<div class="container">
  <hr/>
  <h4 class="sub-title space-left">Companies at {{ location.name }}</h4>
</div>
{% for obj in location.company.all %}
<!--simple card-->
<div class="container">
  <div class="card mx-auto col-md-12 mb-2 ">
    <div class="card-body">
      <div class="row">
        <div class="col-md-4 col-sm-12">
          {% if obj.logo %}
          <a href="{{ obj.get_absolute_url }}">
            <img class="d-block w-100" src='{{ obj.logo.url }}'/>
          </a>
          {% else %}
          <a href="{{ obj.get_absolute_url }}">
            <img class="d-block w-100" src='{% static "img/avatar.svg" %}'>
          </a>s
          {% endif %}
        </div>
        <div class="pull-right col-md-8 col-sm-12">
          <div class="col-md-12 post-header-line">
            <h4 class="card-title">
              <a href="{{ obj.get_absolute_url }}">
                {{ obj.name }}
              </a>
              <span class="badge badge-primary">{{ obj.category.name }}</span>
            </h4>{% if obj.website %}
            <h6 class="card-subtitle mb-2 text-muted"><a href="{{ obj.website}}"> Website </a></h6>
            {% endif %}
            <p class="card-text">{{ obj.description|truncatechars:100 }}...</p>
            <hr/>
            <span><i class="fas fa-star"></i>{{ obj.average_rating | floatformat }} rating </span> |
            <span><i class="fas fa-comments"></i>{{ obj.review_set.count }} reviews</span> |
            {% if obj.location %}
            <span><i class="fas fa-map-marker-alt"></i>{{ obj.location.name }} | {{ obj.location.country.name }}</span>
            {% endif %}
            <div class="pull-right">
              <a class="card-link" href="{{ obj.get_absolute_url }}">
                <button type="button" class="btn btn-primary">Details</button>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--end of simple card-->
{% endfor %}
{% else %}
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">currently no jobs</h5>
    </div>
    <div class="modal-body">
      <a href="{% url 'company:new' %}" class="btn btn-success btn-lg" role="button">Add Your Company </a>
    </div>
  </div>
</div>
{% endif %}

<div class="mb-60"></div>

<!--simple card-->
<div class="container">
  <hr/>
  <h4 class="sub-title space-left">Jobs at {{ location.name }} </h4>
</div>

<div class="mt-5 container">
  {% if location.job.all %}
  {% for obj in location.job.all %}
  <div class="card mx-auto col-md-12 mb-2 ">
    <div class="card-body">
      <div class="row">
        <div class="col-md-3 col-sm-12">
          {% if obj.company.logo %}
          <img alt="..." class="d-block w-100" src='{{ obj.company.logo.url }}'>
          {% else %}
          <img alt="..." class="d-block w-100" src='{% static "img/avatar.svg" %}'>
          {% endif%}
        </div>
        <div class="col-md-9 col-sm-12">
          <div class="row">
            <div class=" col-md-10 post-header-line">
              <h4 class="card-title"><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></h4>
              <h6 class="card-subtitle mb-2 text-muted"><span><i class="far fa-money-bill-alt"></i></span> KES:
                {{obj.salary }}</h6>
            </div>
            <div class="col-md-2 pull-right">
              <a class="card-link" href="{{ obj.get_absolute_url }}">
                <button type="button" class="btn btn-primary">Apply</button>
              </a>
            </div>
          </div>
          <hr/>
          <div class="col-md-12 ">
            <p class="card-text">{{ obj.description|truncatechars:250|linebreaks }}</p>
            {% if obj.tags %}
            {% for tags in obj.tags.all %}
            <span class="badge badge-pill badge-secondary">{{ tags.name }}</span>
            {% endfor %}
            {% endif %}
            <div class="pull-right col-md-4 col-sm-12">
              <i class="fas fa-map-marker-alt"></i> <a> {{ obj.country.name }}, {{ obj.location.name }} </a>
              <i class="far fa-calendar-alt"></i> at Jan/17/2019
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  {% else %}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">currently no jobs</h5>
      </div>
      <div class="modal-body">
        <a href="{% url 'company:new' %}" class="btn btn-success btn-lg" role="button">Add Job Vacancy</a>
      </div>
    </div>
  </div>
  {% endif %}
</div>
<!--end of simple card-->
<div class="mb-60"></div>
{% endblock content %}

templates/location/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}  Location List  | {{ block.super }} {% endblock %}
{% block lead %}
Location List
{% endblock %}
{% block jumbotron %}
<a class="btn btn-common breadcrumb-item active">
  Location List
</a>
<a class="btn btn-common" href='{% url "location:new" %}'>
  new
</a>
{% endblock  %}


{% block content %}

<div class="container">
  {% if location %}

  <div class="row mx-auto ">
    {% for obj in location %}
    <!--card-->
    <div class="card m-2 " style="width: 18rem;">
      {% if obj.photos %}
      <img src='{{ obj.photo.url }}' class='img-responsive card-img-top'/>
      {% else %}
      {% endif %}

      <div class="card-body">
        <h5 class="card-title">{{ obj.name }}</h5>
        <p class="card-text">{{ obj.description|truncatechars:100 }}... </p>
      </div>
      <div class="card-body">
        <a class="card-link btn btn-primary " href="{{ obj.get_absolute_url }}">Details</a>
      </div>
    </div>
    <!--endcard-->
    {% endfor %}
  </div>
  {% else %}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">currently no Location added </h5>
      </div>
      <div class="modal-body">
        <a href="{% url 'location:new' %}" class="btn btn-success btn-lg" role="button">Add New Location</a>
      </div>
    </div>
  </div>
  {% endif %}
</div>


{% if is_paginated %}
<div class="container mx-auto">
  <nav aria-label="modal">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">«</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
      {% else %}
      <li class="disabled">
      </li>
      {% endif %}
      {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
      <li class="page-item active"><a class="page-link"><span>{{ i }}<span class="sr-only">Current</span></span></a>
      </li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a>
      </li>
      {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">»</span>
        <span class="sr-only">Next</span>
      </a>
      </li>
      {% else %}
      <li class="disabled">
      </li>
      {% endif %}
    </ul>
  </nav>
</div>
{% endif %}
{% endblock %}